CREATE DATABASE urlshortner;
USE urlshortner;
CREATE TABLE IF NOT EXISTS urls (
  id INT AUTO_INCREMENT PRIMARY KEY,
  longUrl TEXT NOT NULL,
  shortId VARCHAR(10) UNIQUE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  clicks INT DEFAULT 0
);
SHOW DATABASES;
SHOW TABLES;
DESCRIBE urls;
